### ISSUE TITLE
Credentials Class Refactoring

### ISSUE THREAD

**Issue by BrunoCoimbra** [glideinWMS/glideinwms#258]
We're refactoring the GlideinWMS Credentials class to improve our code and introduce new features. This issue is used to keep track of our progress and receive requests and suggestions from the project's stakeholders.

**New features and improvements**
- [ ] Give more control to operators on how Frontend IDTOKENs are generated
- [ ] Allow operators to specify which credentials are sent where
- [x] Add the possibility to send arbitrary credentials to specific sites
- [x] Treat credential types and functions (what they’re used for) separately
- [x] Factory entries will support a list of required and optional credentials instead of a single auth_method
- [ ] Improve the way the "fair split" method handles multiple credential types

**Bug fixes**
- [ ] Fix an issue that prevents credentials already sent from being updated after a reconfig
- [ ] Fix an issue that causes the HEPCloud Decision Engine to stop updating classads when no jobs are queued
- [ ] https://github.com/glideinWMS/glideinwms/issues/290

**Work Notes**
```[tasklist]
### Tasks
- [ ] https://github.com/glideinWMS/glideinwms/issues/291
- [ ] https://github.com/glideinWMS/glideinwms/issues/294
- [ ] https://github.com/glideinWMS/glideinwms/issues/295
```

**Comment by jasoncpatton** [comment]
Hi again @BrunoCoimbra! To summarize what we talked about after your fantastic HTC23 presentation:

1. I think it would be great if credential purposes could be defined arbitrarily (outside a set of reserved purposes, e.g. `ce_auth` for glidein->CE, `cm_auth` for glidein startd->pool collector, etc.). For example, I could imagine a VO requesting a bunch of different tokens/proxies/etc. being used for testing a bunch of different storage services.
2. For credential discovery, any well-documented method is fine but perhaps the simplest method would be to name the credentials based on their purpose and (as I'm now realizing might be needed) credential type, e.g. `ce_auth.scitoken`, `ce_auth.proxy`, `cm_auth.idtoken`, `cvmfs_auth.scitoken`, `cvmfs_auth.proxy`.
