### ISSUE TITLE
Release 3.11.1

### ISSUE THREAD

**Issue by BrunoCoimbra** [glideinWMS/glideinwms#448]
```[tasklist]
### Tasks
- [ ] https://github.com/glideinWMS/glideinwms/pull/372
- [ ] https://github.com/glideinWMS/glideinwms/issues/443
- [ ] https://github.com/glideinWMS/glideinwms/issues/444
- [ ] https://github.com/glideinWMS/glideinwms/issues/371
- [ ] https://github.com/glideinWMS/glideinwms/pull/434
```

**Comment by namrathaurs** [comment]
Closing this as the final release for 3.11.1 was completed; released on 7/29.
