### ISSUE TITLE
Release 3.10.8

### ISSUE THREAD

**Issue by BrunoCoimbra** [glideinWMS/glideinwms#458]
```[tasklist]
### Tasks
- [ ] https://github.com/glideinWMS/glideinwms/issues/444
- [ ] https://github.com/glideinWMS/glideinwms/issues/371
- [ ] https://github.com/glideinWMS/glideinwms/pull/451
- [ ] https://github.com/glideinWMS/glideinwms/pull/415
- [ ] https://github.com/glideinWMS/glideinwms/pull/434
- [ ] https://github.com/glideinWMS/glideinwms/pull/459
- [ ] https://github.com/glideinWMS/glideinwms/pull/460
```

**Comment by namrathaurs** [comment]
Release completed on Nov 25, 2024. Closing this out!
