### ISSUE TITLE
Release 3.10.9

### ISSUE THREAD

**Issue by namrathaurs** [glideinWMS/glideinwms#469]
```[tasklist]
### Tasks
- [ ] https://github.com/glideinWMS/glideinwms/issues/222
- [ ] https://github.com/glideinWMS/glideinwms/pull/465
- [ ] https://github.com/glideinWMS/glideinwms/pull/466
- [ ] https://github.com/glideinWMS/glideinwms/pull/467
- [ ] https://github.com/glideinWMS/glideinwms/pull/468
- [ ] https://github.com/glideinWMS/glideinwms/issues/398
- [ ] https://github.com/glideinWMS/glideinwms/pull/471
- [ ] https://github.com/glideinWMS/glideinwms/pull/472
- [ ] https://github.com/glideinWMS/glideinwms/pull/473
- [ ] https://github.com/glideinWMS/glideinwms/pull/475
- [ ] https://github.com/glideinWMS/glideinwms/pull/474
```

**Comment by namrathaurs** [comment]
Release completed on Jan 16, 2025. Closing this out!
